version: '3'
services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: my_mongo
    volumes:
      - ./data/mongodb:/data/db