version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    networks:
      - net

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    networks:
      - net

  trip:
    build:
      context: trip
      dockerfile: Dockerfile
    networks:
      - net
    depends_on:
      - kafka
      - offering

  offering:
    build:
      context: offering
      dockerfile: Dockerfile
    networks:
      - net

  tmp:
    build:
      context: tmp
      dockerfile: Dockerfile
    networks:
      - net

networks:
  net:
