{
 "title": "Final Project",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "OfferingSvc total requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "requests_total{method=\"getOffer\"}",
     "legendFormat": "GetOffer"
    },
    {
     "expr": "requests_total{method=\"createOffer\"}",
     "legendFormat": "CreateOffer"
    }
   ]
  },
  {
   "title": "ClientSvc total requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "requests_total{method=\"CreateTrip\"}",
     "legendFormat": "CreateTrip"
    },
    {
     "expr": "requests_total{method=\"GetTripByID\"}",
     "legendFormat": "GetTripByID"
    },
    {
     "expr": "requests_total{method=\"ListTrips\"}",
     "legendFormat": "ListTrips"
    },
    {
     "expr": "requests_total{method=\"CancelTrip\"}",
     "legendFormat": "CancelTrip"
    }
   ]
  },
  {
   "title": "ClientSvc response time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "response_time{method=\"CancelTrip\"}",
     "legendFormat": "CancelTrip"
    },
    {
     "expr": "response_time{method=\"CreateTrip\"}",
     "legendFormat": "CreateTrip"
    },
    {
     "expr": "response_time{method=\"GetTripByID\"}",
     "legendFormat": "GetTripByID"
    },
    {
     "expr": "response_time{method=\"ListTrips\"}",
     "legendFormat": "ListTrips"
    }
   ]
  }
 ]
}