apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: http://postgres:5432
    user: admin
    secureJsonData:
      password: 'password'
    jsonData:
      database: postgres
      sslmode: 'disable'

  - name: MongoDB
    type: mongodb
    access: proxy
    url: http://mongodb:27017
    jsonData:
      database: my_mongo

  - name: Jaeger
    type: jaeger
    url: http://jaeger:16686